version: '3.7'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_TYPE=postgres
      - MB_DB_DBNAME=metabase
      - MB_DB_PORT=5432
      - MB_DB_USER=metabase
      - MB_DB_PASS=metabase_password
      - MB_DB_HOST=postgres-db
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:12
    container_name: postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=metabase
      - POSTGRES_PASSWORD=metabase_password
      - POSTGRES_DB=metabase
    ports:
      - "6543:5432"

volumes:
  postgres-data:
